# Setup front-end load balancer tier
- name: setup load-balancer tier
  hosts: frontends
  become: yes
  roles:
    - {name: aws_base_config, tags: aws_base_config}
    - {name: lb-tier, tags: [lbs, haproxy]}

## Setup application servers tier
- name: setup app tier
  hosts: apps
  become: yes
  gather_facts: false
  roles:
    - {name: aws_base_config, tags: aws_base_config}
    - {name: app-tier, tags: [apps, tomcat]}

# Setup database tier
- name: setup database tier
  become: yes
  hosts: appdbs
  roles:
    - {name: aws_base_config, tags: aws_base_config}
    - {name: db-tier, tags: [dbs, postgres]}
